# Generated by Django 5.2.4 on 2025-10-27 15:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_resolucion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True)),
                ('tipo_incidencia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioTerritorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion', models.CharField(max_length=255)),
                ('prioridad', models.CharField(max_length=50)),
                ('nombre_vecino', models.CharField(max_length=200)),
                ('telefono_vecino', models.CharField(max_length=20)),
                ('correo_vecino', models.EmailField(blank=True, max_length=254)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_multimedia', models.CharField(max_length=50)),
                ('ruta', models.FileField(upload_to='multimedia_incidencias/')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.encuesta')),
            ],
        ),
    ]
