# Generated by Django 5.2.4 on 2025-11-23 08:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0002_departamento_activo_direccion_activa_and_more'),
        ('usuarios', '0002_usuario_esta_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion', models.CharField(max_length=255)),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], max_length=50)),
                ('nombre_vecino', models.CharField(max_length=200)),
                ('telefono_vecino', models.CharField(max_length=20)),
                ('correo_vecino', models.EmailField(blank=True, max_length=254)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_multimedia', models.CharField(max_length=50)),
                ('ruta', models.FileField(upload_to='multimedia_incidencias/')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True)),
                ('tipo_incidencia', models.CharField(max_length=100)),
                ('cuadrilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacion.cuadrilla')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_resolucion', models.DateTimeField(default=django.utils.timezone.now)),
                ('cuadrilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizacion.cuadrilla')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=500)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.solicitud')),
            ],
        ),
        migrations.AddField(
            model_name='encuesta',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.solicitud'),
        ),
        migrations.CreateModel(
            name='UsuarioTerritorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacion.departamento')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.solicitud')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'unique_together': {('solicitud', 'departamento', 'usuario')},
            },
        ),
    ]
