# Generated by Django 5.2.4 on 2025-11-02 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0001_initial'),
        ('usuarios', '0002_usuario_esta_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='resolucion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('CREADA', 'Creada'), ('ABIERTA', 'Abierta'), ('DERIVADA', 'Derivada'), ('EN PROCESO', 'En Proceso'), ('FINALIZADA', 'Finalizada'), ('RECHAZADA', 'Rechazada')], default='CREADA', max_length=50),
        ),
    ]
