# Generated by Django 5.2.4 on 2025-10-27 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidencias', '0001_initial'),
        ('organizacion', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolucion',
            name='cuadrilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizacion.cuadrilla'),
        ),
        migrations.AddField(
            model_name='resolucion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='cuadrilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacion.cuadrilla'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.solicitud'),
        ),
        migrations.AddField(
            model_name='resolucion',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.solicitud'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.solicitud'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.solicitud'),
        ),
        migrations.AddField(
            model_name='usuarioterritorial',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacion.departamento'),
        ),
        migrations.AddField(
            model_name='usuarioterritorial',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.solicitud'),
        ),
        migrations.AddField(
            model_name='usuarioterritorial',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='usuarioterritorial',
            unique_together={('solicitud', 'departamento', 'usuario')},
        ),
    ]
