# Generated by Django 5.2.4 on 2025-11-06 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_alter_encuesta_prioridad'),
        ('usuarios', '0002_usuario_esta_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario'),
        ),
    ]
