# Generated by Django 5.2.4 on 2025-11-02 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_encuesta_activa_encuesta_fecha_actualizacion_and_more'),
        ('incidencias', '0002_initial'),
    ]

    operations = [
    ]
