<<<<<<< HEAD
# Generated by Django 5.2.4 on 2025-10-01 23:01
=======
# Generated by Django 5.2.4 on 2025-10-27 15:44
>>>>>>> 29efc874b2544b2b93fd82a96d1864161b6d4137

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_encargado', models.CharField(max_length=200)),
                ('correo_encargado', models.EmailField(max_length=254)),
<<<<<<< HEAD
                ('departamento', models.CharField(max_length=200)),
=======
                ('departamento', models.CharField(max_length=200, verbose_name='Departamento')),
                ('activo', models.BooleanField(default=True, verbose_name='Departamento Activo')),
>>>>>>> 29efc874b2544b2b93fd82a96d1864161b6d4137
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_encargado', models.CharField(max_length=200)),
                ('correo_encargado', models.EmailField(max_length=254)),
                ('nombre_direccion', models.CharField(max_length=255)),
<<<<<<< HEAD
=======
                ('activa', models.BooleanField(default=True, verbose_name='Dirección Activa')),
>>>>>>> 29efc874b2544b2b93fd82a96d1864161b6d4137
            ],
        ),
        migrations.CreateModel(
            name='Cuadrilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cuadrilla', models.CharField(max_length=200)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacion.departamento')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacion.direccion'),
        ),
        migrations.CreateModel(
            name='EncargadoDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacion.departamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='EncargadoDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacion.direccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioCuadrilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuadrilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacion.cuadrilla')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'cuadrilla')},
            },
        ),
    ]
