# Generated by Django 5.2.4 on 2025-10-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Departamento Activo'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Dirección Activa'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='departamento',
            field=models.CharField(max_length=200, verbose_name='Departamento'),
        ),
    ]
